:doctype: book
:icons: font
:hide-uri-scheme:


= Access to vSphere

In order for machine config operator to interact with the vSphere API, we need to expose the endpoint to the Openshift nodes.

In vSphere, you can add a total of 4 network adapters on the appliance. Second adapter will be earmarked for VCHA, so if needed you have to add an additional adapter to configure.

Make sure that the hostname specified to access vCenter, resolves within the subnet as the ip address specified on the third adapter.

NOTE: VMware VCSA 7 multiple network adapters https://4sysops.com/archives/vmware-vcsa-7-multiple-network-adapters/

= DNS
On a node, with a fixed ip in the disconnected network, install dns. In this example 10.0.0.2. 

As root install dnsmasq
[code]
----
dnf install -y dnsmasq
----

Create /etc/dnsmasq.d/openshift-4.conf, where 10.0.0.6 is our apps wildcard, and "do" is our cluster name (disconnected "OpenShift").

[code]
----
strict-order
domain=pl.pietersmalan.com
expand-hosts
server=10.0.0.2
interface=ens224
address=/apps.do.pl.pietersmalan.com/10.0.0.6
addn-hosts=/etc/dnsmasq-openshift-4.addnhosts
----

Add the dns entries for OpenShift, .5 for API, and the vSphere ip from previous step:

/etc/dnsmasq-openshift-4.addnhosts
[code]
----
10.0.0.5 api.do.pl.pietersmalan.com api-int.do.pl.pietersmalan.com
10.0.0.2 bastion.pietersmalan.com bastion.pl.pietersmalan.com
10.0.0.250 vcsa.pietersmalan.com
----


= DHCP
DHCP is required.

[code]
----
dnf -y install dhcp-server
----

[code]
----
vi /etc/dhcp/dhcpd.conf
----

[code]
----
#
# DHCP Server Configuration file.
#   see /usr/share/doc/dhcp-server/dhcpd.conf.example
#   see dhcpd.conf(5) man page
#
# Set DNS name and DNS server's IP address or hostname
DHCPDARGS="ens224";
option domain-name     "pl.pietersmalan.com";
option domain-name-servers 10.0.0.2;

# Declare DHCP Server
authoritative;

# The default DHCP lease time
default-lease-time 600;

# Set the maximum lease time
max-lease-time 7200;

# Set Network address, subnet mask and gateway

subnet 10.0.0.0 netmask 255.255.255.0 {
    # Range of IP addresses to allocate
    range dynamic-bootp 10.0.0.10 10.0.0.200;
    # Provide broadcast address
    option broadcast-address 10.0.0.255;
    # Set default gateway
    option routers 10.0.0.1;
}
----

[code]
----
systemctl enable --now dhcpd
----